// NeoMe project tracker data — updated by Claude as workstreams progress.
// Edit this file (not tracker.html) when status changes.
// Schema is informal; the renderer is forgiving of missing fields.

window.TRACKER = {
  lastUpdated: "2026-05-04",

  blockers: [
    {
      what: "Recipe schema decision",
      blockedOn: "Gabi",
      action: "Review nutrition-curated.csv (top 150 ingredients)",
      since: "2026-04-30",
    },
    {
      what: "Exercise video URLs",
      blockedOn: "Gabi",
      action: "Provide video URLs for all exercises so schedules can be fully built in admin",
      since: "2026-05-04",
    },
  ],

  workstreams: [
    {
      id: "programmes-content",
      title: "Programmes — content build (Gabi)",
      pillar: "telo",
      status: "in-progress",
      owner: "Gabi",
      summary: "Admin infrastructure is fully built (schedule builder, exercise/meditation pickers, status enum, cover upload). Gabi now takes over to populate content. Steps: (1) seed the 4 programmes via Admin → Programy, (2) upload exercise thumbnails + provide video URLs, (3) build the week-by-week schedule for each programme assigning exercises and meditations to each day slot. Once schedules are saved, the dev work to wire the user-facing TeloPrograms and ProgramDetail pages to Supabase can begin.",
      blocker: "Exercise video URLs not yet provided",
      nextAction: "Gabi: seed programmes → upload exercise thumbnails → provide video URLs → build schedules in admin panel",
      contentSteps: [
        { label: "Seed 4 programmes (Postpartum, BodyForming, ElasticBands, Strong&Sexy)", status: "pending", owner: "Gabi", note: "Admin → Programy → 'Seed 4 programy'" },
        { label: "Upload cover images for each programme", status: "pending", owner: "Gabi" },
        { label: "Upload exercise thumbnails (24 exercises + 16 stretches)", status: "pending", owner: "Gabi", note: "Admin → Cvičenia → each row → thumbnail upload" },
        { label: "Provide exercise video URLs", status: "pending", owner: "Gabi", note: "Paste URLs into Admin → Cvičenia → video URL field" },
        { label: "Build 8-week schedule for Postpartum", status: "pending", owner: "Gabi" },
        { label: "Build 6-week schedule for BodyForming", status: "pending", owner: "Gabi" },
        { label: "Build 6-week schedule for ElasticBands", status: "pending", owner: "Gabi" },
        { label: "Build 6-week schedule for Strong&Sexy", status: "pending", owner: "Gabi" },
        { label: "Wire TeloPrograms + ProgramDetail to Supabase (replace static data)", status: "pending", owner: "Dev", note: "Dev task — unblocked once at least 1 schedule is complete" },
      ],
    },
    {
      id: "admin-rebuild",
      title: "Admin panel rebuild",
      pillar: "telo",
      status: "in-progress",
      summary: "Phases 0–3 shipped. Foundation, blog editor, exercises/meditations, and programmes schedule builder are all done. Remaining: messaging UI, user management, and stats dashboard.",
      blocker: null,
      nextAction: "Phase 4: Messaging UI (inbox thread view for admin) + User management tab. Phase 5: Stats dashboard.",
      timeline: "~2 weeks remaining (phases 4–5)",
      phases: [
        { id: 0, label: "Foundation — migrations, Edge Function, Storage bucket, React Query, admin auth", status: "shipped", weeks: "Week 1" },
        { id: 1, label: "Blog posts — rich text editor, image upload, user-facing rendering", status: "shipped", weeks: "Week 2" },
        { id: 2, label: "Exercises + Meditations (status enum, thumbnail upload)", status: "shipped", weeks: "Weeks 3-4" },
        { id: 3, label: "Programmes schedule builder", status: "shipped", weeks: "Week 5" },
        { id: 4, label: "Messaging UI + User management", status: "pending", weeks: "Week 6" },
        { id: 5, label: "Stats dashboard", status: "pending", weeks: "Week 7" },
      ],
      links: [
        { label: "Phase 0 plan", href: ".claude/plans/admin-phase-0-foundation.md" },
        { label: "Design decisions (memory)", href: "memory/project_admin_panel_plan.md" },
      ],
    },
    {
      id: "recipe-pipeline",
      title: "Recipe parser pipeline",
      pillar: "strava",
      status: "blocked",
      owner: "Gabi",
      summary: "Convert Gabi's 20 client meal-plan CSVs into a curated NeoMe recipe library. 1913 recipes parsed and deduped, ingredient normalisation done. Currently waiting on Gabi's nutrition values review.",
      blocker: "Gabi reviewing nutrition-curated.csv",
      nextAction: "Gabi saves nutrition-reviewed.csv → Claude applies values + runs authoring gate",
      stages: [
        { label: "Parse 20 CSVs", status: "done", note: "2763 raw blocks" },
        { label: "Clean + dedup", status: "done", note: "2085 recipes, 1170 ingredients" },
        { label: "Ingredient normalisation template", status: "done" },
        { label: "Apply Gabi's normalisation", status: "done", note: "54 edits, 47 IGNOREs" },
        { label: "Strip false-positive titles", status: "done", note: "1913 recipes" },
        { label: "OpenFoodFacts auto-match", status: "abandoned", note: "16% — pivoted to hand-curated" },
        { label: "Hand-curated nutrition table (top 150)", status: "blocked", note: "Awaiting Gabi review" },
        { label: "Apply nutrition to all recipes", status: "pending" },
        { label: "Compute sub-recipe nutrition", status: "pending" },
        { label: "Authoring gate (30/40/30 ± 5%)", status: "pending" },
        { label: "Send pass/adjust/skip report", status: "pending" },
        { label: "Define recipes table schema", status: "pending", note: "Locks recipes admin tab" },
        { label: "Import to Supabase", status: "pending" },
      ],
      links: [
        { label: "Pipeline state (memory)", href: "memory/project_recipe_pipeline_state.md" },
        { label: "Nutrition strategy", href: "memory/project_nutrition_strategy_2026.md" },
        { label: "Output: recipes-final.json", href: "data/parsed/recipes-final.json" },
        { label: "Pending: nutrition-curated.csv", href: "data/parsed/nutrition-curated.csv" },
      ],
    },
    {
      id: "nutrition-onboarding",
      title: "Nutrition onboarding (R7)",
      pillar: "strava",
      status: "shipped",
      summary: "NutritionOnboarding redesigned with energy-range calorie display (lowCal–highCal per day) and 3-way life phase radio (regular / postpartum / pregnant). Postpartum reveals breastfeeding follow-up. Summary shows full TDEE breakdown. Macros off midpoint. Gabi to review logic and copy before going live with users.",
      blocker: null,
      nextAction: "Gabi: review onboarding flow + calorie calculation logic. Wire profile to meal-plan generator once recipe pipeline finishes.",
      owner: "Gabi review",
    },
    {
      id: "period-tracker",
      title: "Period tracker (Periodka)",
      pillar: "periodka",
      status: "shipped",
      summary: "Fully shipped including Supabase sync. cycle_data syncs via user_app_data table. Symptom chips sync via cycle_symptoms table. Gabi to confirm the cycle phase logic and symptom list covers her clinical needs before launch.",
      blocker: null,
      nextAction: "Gabi: verify phase logic and symptom list. Dev: cleanup opportunity — delete dead tracker components + Periodka.old.tsx.",
      owner: "Gabi review",
    },
    {
      id: "design-system",
      title: "R12 design system rollout",
      pillar: "mysel",
      status: "shipped",
      summary: "All 4 PRs committed. Tokens, shadcn reskin, component library, and trial screens applied across Blog, Periodka, TeloPrograms, ProgramDetail. Wave 2 (Strava, Myseľ, Cyklus screens) awaits next handoff batch from Claude Design.",
      blocker: null,
      nextAction: "Wave 2 screens when next handoff batch arrives.",
    },
    {
      id: "stripe-checkout",
      title: "Stripe live checkout",
      pillar: "telo",
      status: "blocked",
      summary: "Scaffolded but not wired live. €79 meal plan + €30 discount UI not built.",
      blocker: "Post-MVP priority",
      nextAction: "Defer until after launch",
    },
  ],

  // What Gabi owns right now
  gabiTasks: [
    { priority: 1, task: "Seed + build programme schedules", where: "Admin → Programy", detail: "Seed 4 programmes, upload cover images, upload exercise thumbnails, provide video URLs, then build week×day schedules for all 4 programmes." },
    { priority: 2, task: "Review nutrition-curated.csv", where: "data/parsed/nutrition-curated.csv", detail: "Fill in kcal, protein, carbs, fat for the top 150 ingredients. Save as nutrition-reviewed.csv. This unblocks the recipe pipeline and the Strava hub." },
    { priority: 3, task: "Review nutrition onboarding flow", where: "App → Strava → onboarding", detail: "Check calorie range logic, life phase copy, and breastfeeding bonus feels clinically correct." },
    { priority: 4, task: "Verify Periodka phase logic + symptom list", where: "App → Periodka", detail: "Confirm the 4 cycle phases and symptom chips cover the clinical needs for the target audience." },
  ],

  backlog: [
    { tier: "high", label: "Wire TeloPrograms/ProgramDetail to Supabase", note: "Replace static src/data/programs.ts — unblocked once 1 schedule is built" },
    { tier: "high", label: "Webhooks for external integrations", note: "ActiveCampaign on programme completion, etc." },
    { tier: "high", label: "Per-client recipe scaling", note: "Depends on recipe pipeline finishing" },
    { tier: "high", label: "Engagement dashboard", note: "Stats Option B — cohort retention, funnels" },
    { tier: "high", label: "PDF export for JedalnicekPlanner", note: "jsPDF already installed" },
    { tier: "high", label: "Live Stripe checkout", note: "€79 meal plan + €30 discount" },
    { tier: "medium", label: "Cron safety-net for scheduled inbox messages" },
    { tier: "medium", label: "Scheduled-publish for blog posts" },
    { tier: "medium", label: "Content versioning / revisions" },
    { tier: "medium", label: "Admin Phase 4: Messaging UI + User management" },
    { tier: "medium", label: "Admin Phase 5: Stats dashboard" },
    { tier: "low", label: "Old screen cleanup PR (delete *.old.tsx)" },
    { tier: "low", label: "Admin audit log table" },
    { tier: "low", label: "Bulk import UI for content tables" },
  ],

  recentDecisions: [
    { date: "2026-05-04", what: "Programmes content build handed to Gabi. Admin infrastructure (schedule builder, pickers, status) is dev-complete. Gabi seeds programmes, uploads assets, provides video URLs, and builds schedules. Dev resumes to wire user-facing pages once first schedule is done." },
    { date: "2026-05-04", what: "Nutrition onboarding + Periodka tracker handed to Gabi for clinical review before going live with users." },
    { date: "2026-05-04", what: "Admin Phase 3 shipped: Programmes schedule builder with week×day editor, exercise/meditation content pickers, optional Gabi message per day, status enum, cover image upload." },
    { date: "2026-05-04", what: "Nutrition onboarding (R7): energy range replaces single dailyCalories. Life phase radio (regular/postpartum/pregnant) replaces binary isPregnant." },
    { date: "2026-05-04", what: "Phase 2 shipped: ExercisesTab + MeditationsTab — status enum, thumbnail upload, cycleStatus badge. Video URLs deferred." },
    { date: "2026-05-03", what: "Phase 1 shipped: Tiptap rich text editor, blog wired to Supabase." },
    { date: "2026-05-02", what: "Phase 0 fully shipped: Edge Function deployed, admin role confirmed, Storage bucket live." },
    { date: "2026-04-30", what: "Recipe pipeline: pivoted from OpenFoodFacts to hand-curated nutrition." },
    { date: "2026-04-30", what: "Editorial rule: no juices in recipes (lemon as flavouring OK)." },
    { date: "2026-04-29", what: "Recipe pipeline kicked off — 67k lines parsed → 1913 deduped recipes." },
    { date: "2026-04-25", what: "Gamification dropped from nutrition strategy. Editorial tone confirmed." },
    { date: "2026-04-23", what: "Nutrition strategy redesign: curated library + energy range + cycle awareness." },
  ],
};
