#!/usr/bin/env python3
"""
NeoMe recipe importer — Phase 3: Supabase SQL seed.

Reads recipes_with_macros.json and emits seed_recipes.sql — a single
transaction that replaces public.recipes with the 225 imported recipes.

Target schema (supabase/migrations/20260507100000_recipes_library.sql):
  name, slot, prep_minutes, instructions, ingredients(jsonb),
  kcal, protein, carbs, fat, fiber, coverage_pct, usage_count, active
"""
import json
from pathlib import Path

HERE = Path(__file__).parent
IN = HERE / "recipes_with_macros.json"
OUT = HERE / "seed_recipes.sql"


def q(s):
    """SQL single-quoted string literal (None → NULL)."""
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def jsonb(obj):
    """JSON literal cast to jsonb."""
    return q(json.dumps(obj, ensure_ascii=False)) + "::jsonb"


def main():
    recipes = json.loads(IN.read_text(encoding="utf-8"))

    lines = []
    lines.append("-- NeoMe recipe library — generated by recipe-import pipeline.")
    lines.append(f"-- {len(recipes)} recipes from the 3-card source document (1. séria).")
    lines.append("-- Apply in the Supabase SQL editor. Wrapped in a transaction.")
    lines.append("")
    lines.append("begin;")
    lines.append("")
    lines.append("-- replace the whole library (pre-launch — no real user data depends on it)")
    lines.append("delete from public.recipes;")
    lines.append("")
    lines.append("insert into public.recipes")
    lines.append("  (name, slot, prep_minutes, instructions, ingredients,")
    lines.append("   kcal, protein, carbs, fat, fiber, coverage_pct, usage_count, active)")
    lines.append("values")

    rows = []
    for r in recipes:
        ings = [{"raw": i["raw"], "name": i["name"], "grams": i["grams"]}
                for i in r["ingredients"]]
        prep = r["prep_minutes"] if r["prep_minutes"] is not None else "NULL"
        row = (
            f"  ({q(r['name'])}, {q(r['slot'])}, {prep}, "
            f"{q(r['instructions'])},\n"
            f"   {jsonb(ings)},\n"
            f"   {r['kcal']}, {r['protein']}, {r['carbs']}, {r['fat']}, "
            f"{r['fiber']}, {r['coverage_pct']}, 1, true)"
        )
        rows.append(row)

    lines.append(",\n".join(rows) + ";")
    lines.append("")
    lines.append("commit;")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")

    # summary
    from collections import Counter
    by_slot = Counter(r["slot"] for r in recipes)
    print(f"=== SQL SEED WRITTEN — {OUT.name} ===")
    print(f"  recipes: {len(recipes)}")
    for slot in ("ranajky", "hlavne", "snack"):
        print(f"    {slot:9s}: {by_slot[slot]}")
    print(f"  file size: {OUT.stat().st_size / 1024:.1f} KB")


if __name__ == "__main__":
    main()
